services:
  - type: web
    name: erp-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build:server
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: AUTH_SECRET
        generateValue: true